---
- name: Download WordPress  
  get_url: 
    url=https://wordpress.org/latest.tar.gz
    dest=/tmp/wordpress.tar.gz
    validate_certs=no

- name: Create kittle web folder
  file: path=/var/www/kittle state=directory owner=www-data group=www-data mode=0775

- name: Create portraits web folder
  file: path=/var/www/portraits state=directory owner=www-data group=www-data mode=0775

- name: Create families web folder
  file: path=/var/www/families state=directory owner=www-data group=www-data mode=0775

- name: Create weddings web folder
  file: path=/var/www/weddings state=directory owner=www-data group=www-data mode=0775

- name: Create landscape/urban web folder
  file: path=/var/www/vistas state=directory owner=www-data group=www-data mode=0775

- name: Create donkittle web folder
  file: path=/var/www/donkittle state=directory owner=www-data group=www-data mode=0775

- name: Extract WordPress for kittle.ca
  unarchive: src=/tmp/wordpress.tar.gz 
    dest=/var/www/kittle
    creates=/var/www/kittle/wordpress
    copy=no
    owner=www-data 
    group=www-data 
    mode=0775

- name: Extract WordPress for donkittleportraits.com
  unarchive: src=/tmp/wordpress.tar.gz 
    dest=/var/www/portraits
    creates=/var/www/portraits/wordpress
    copy=no
    owner=www-data 
    group=www-data 
    mode=0775

- name: Extract WordPress for donkittlefamilies.com
  unarchive: src=/tmp/wordpress.tar.gz 
    dest=/var/www/families
    creates=/var/www/families/wordpress
    copy=no
    owner=www-data 
    group=www-data 
    mode=0775

- name: Extract WordPress for donkittleweddings.com
  unarchive: src=/tmp/wordpress.tar.gz
    dest=/var/www/weddings
    creates=/var/www/weddings/wordpress
    copy=no
    owner=www-data 
    group=www-data 
    mode=0775

- name: Extract WordPress for donkittlevistas.com
  unarchive: src=/tmp/wordpress.tar.gz
    dest=/var/www/vistas
    creates=/var/www/vistas/wordpress
    copy=no
    owner=www-data 
    group=www-data 
    mode=0775

- name: Extract WordPress for donkittle code blog
  unarchive: src=/tmp/wordpress.tar.gz
    dest=/var/www/donkittle
    creates=/var/www/donkittle/wordpress
    copy=no
    owner=www-data 
    group=www-data 
    mode=0775

- command: /bin/true
  notify:
  - restart apache2


